JWT="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIyMDk0ZDcyYS03ZTQ0LTQ1MjgtOWEyNy04YmFjNDVjZjllN2IiLCJlbWFpbCI6InN1cHJlbWVhamFsYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiYjRmYTg3NDI0YjVkOGE2Zjg0MzMiLCJzY29wZWRLZXlTZWNyZXQiOiJjZDZjZTA5OGFlMGJmZTZiNmNhNTcwYTc2ZWE5NmY3NmEwZmY4NWZlZmVmMTUxZTlhOWNiZjE0YTQ5MjBjNmZlIiwiZXhwIjoxODA5NDQ0MDMzfQ._Fp5eKeHXus43GRFrqHMxK_4PrhDOY8ZkdcOwi8nA_s"

echo -e "\nTesting direct Pinata upload with frontend JWT..."
curl -i -F "file=@contract/README.md" \
  -H "Authorization: Bearer $JWT" \
  https://api.pinata.cloud/pinning/pinFileToIPFS 2>&1 | head -30
